name: Release
on:
  schedule:
    - cron: "25 9 */3 * *"
permissions:
  id-token: write
  contents: write
jobs:
  release:
    name: Updates languages, releases a new version if needed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Install Node
        id: install_node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        id: install_dependencies
        run: |
          npm install

      - name: Update languages
        id: update
        run: |
          GOOGLE_KEY=${{ secrets.GOOGLE_KEY }} npm run update

      - name: Test
        id: test
        if: ${{ steps.update.outputs.status == 'updated' }}
        run: |
          npm run test

      - name: Bump version
        id: bump_version
        if: ${{ steps.update.outputs.status == 'updated' }}
        run: |
          npm run bump_version

      - name: Release
        id: release
        if: ${{ steps.update.outputs.status == 'updated' }}
        run: |
          npm run release

      - name: Publish
        id: publish
        if: ${{ steps.update.outputs.status == 'updated' }}
        run: |
          npm publish